// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR6ojDWXQjRW6wcmNu7P53ckDoIXlEZs8',
    appId: '1:220692921472:web:c7ee6de6af3e50e554ba65',
    messagingSenderId: '220692921472',
    projectId: 'fitness-app-dfa39',
    authDomain: 'fitness-app-dfa39.firebaseapp.com',
    storageBucket: 'fitness-app-dfa39.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmhZeyxY0NmsKgzYDlAQIwKg3EXsruKwI',
    appId: '1:220692921472:android:c4774e39ae9f736454ba65',
    messagingSenderId: '220692921472',
    projectId: 'fitness-app-dfa39',
    storageBucket: 'fitness-app-dfa39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC84aq17ifDBqQve7LxVcrfQvt3PV9TGNE',
    appId: '1:220692921472:ios:fc1b751aa87fdef054ba65',
    messagingSenderId: '220692921472',
    projectId: 'fitness-app-dfa39',
    storageBucket: 'fitness-app-dfa39.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC84aq17ifDBqQve7LxVcrfQvt3PV9TGNE',
    appId: '1:220692921472:ios:fc1b751aa87fdef054ba65',
    messagingSenderId: '220692921472',
    projectId: 'fitness-app-dfa39',
    storageBucket: 'fitness-app-dfa39.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR6ojDWXQjRW6wcmNu7P53ckDoIXlEZs8',
    appId: '1:220692921472:web:c3b2114997ce382354ba65',
    messagingSenderId: '220692921472',
    projectId: 'fitness-app-dfa39',
    authDomain: 'fitness-app-dfa39.firebaseapp.com',
    storageBucket: 'fitness-app-dfa39.firebasestorage.app',
  );
}
